timekeeping/urls.py
from django.urls import path
from timekeeping.views import TimeTableView, TimeInputPartialView

app_name = 'timekeeping'

urlpatterns = [
    path('', TimeTableView.as_view(), name='time-table'),
    path('create/', TimeInputPartialView.as_view(), name='time-input'),
]

toppytime/urls.py
from django.urls import path, include

urlpatterns = [
    path('timekeeping/', include('timekeeping.urls')),
]

timekeeping/models.py
from django.db import models


class TimeEntry(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    class Meta:
        ordering = ('end_time',)

    def hours(self):
        delta = self.end_time - self.start_time

        hours_rounded = 0
        total_seconds = delta.total_seconds()
        while total_seconds > 7.5 * 60:
            hours_rounded += .25
            total_seconds -= 15 * 60

        return hours_rounded

timekeeping/forms.py
from django.forms import ModelForm, DateTimeInput, ValidationError
from timekeeping.models import TimeEntry


class CustomDateTimeWidget(DateTimeInput):
    input_type = 'datetime-local'


class TimeEntryForm(ModelForm):
    class Meta:
        model = TimeEntry
        fields = '__all__'
        widgets = {
            'start_time': CustomDateTimeWidget,
            'end_time': CustomDateTimeWidget,
        }

    def clean(self):
        cleaned_data = super(TimeEntryForm, self).clean()

        start_time = cleaned_data['start_time']
        end_time = cleaned_data['end_time']

        if start_time >= end_time:
            raise ValidationError('Start Time must be before End Time!')

        return cleaned_data

timekeeping/views.py
import datetime

from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView

from .models import TimeEntry
from .forms import TimeEntryForm


def get_sunday(date):
    # https://stackoverflow.com/questions/18200530/get-the-last-sunday-and-saturdays-date-in-python
    idx = (date.weekday() + 1) % 7
    sun = date - datetime.timedelta(idx)
    return sun


class TimeTableView(TemplateView):
    template_name = 'timekeeping/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # https://stackoverflow.com/questions/4668619/how-do-i-filter-query-objects-by-date-range-in-django
        context['time_entries'] = TimeEntry.objects.filter(end_time__gte=get_sunday(datetime.date.today()))
        context['total_hours'] = sum(t.hours() for t in context['time_entries'])
        form = TimeEntryForm()
        context['form'] = form
        return context


class TimeInputPartialView(View):
    def get_model(self):
        model = None
        if self.request.GET:
            product_id = self.request.GET.get('id', None)
            if product_id:
                model = TimeEntry.objects.get(pk=product_id)
        return model

    def get_form(self):
        if self.request.POST:
            form = TimeEntryForm(self.request.POST)
        else:
            initial_model = self.get_model()
            form = TimeEntryForm(instance=initial_model)
        return form

    def get(self, request):
        context = {
            'form': self.get_form()
        }
        return render(request, 'timekeeping/partials/', context)

    def post(self, request):
        form = self.get_form()
        if form.is_valid():
            print('Form is valid!')
            form.save()
            form = TimeEntryForm()
        today = datetime.date.today()
        idx = (today.weekday() + 1) % 7
        sun = today - datetime.timedelta(idx)
        context = {
            'time_entries': TimeEntry.objects.filter(end_time__gte=get_sunday(datetime.date.today())),
            'form': form
        }
        context['total_hours'] = sum(t.hours() for t in context['time_entries'])
        return render(request, 'timekeeping/partials/time_entry_form_post.html', context)

templates/timekeeping/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Tier42's Timekeeping Solution">
        <meta name="htmx-config" content='{"useTemplateFragments":true}'>

        <title>ToppyTime</title>
        <link href="{% static '/vendor/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static '/vendor/material-icons/iconfont/material-icons.css' %}" rel="stylesheet">
        <link href="{% static '/vendor/tom-select/dist/css/tom-select.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static '/vendor/vanillajs-datepicker/dist/css/datepicker.min.css' %}">
        {% block styles %}{% endblock %}
    </head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <script src="{% static '/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static '/vendor/htmx.org/dist/htmx.min.js' %}"></script>
        <script src="{% static '/vendor/tom-select/dist/js/tom-select.complete.min.js' %}"></script>
        <script src="{% static '/vendor/vanillajs-datepicker/dist/js/datepicker-full.min.js' %}"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

templates/timekeeping/dashboard.html
{% extends 'timekeeping/base.html' %}

{% block content %}

    {% include 'timekeeping/partials/time_entry_form_post.html' %}

{% endblock %}

templates/timekeeping/partials/create_time_entry.html
{# Gives a form with start and end times for TimeEntry Models #}
{# expects a context variable named "id" that is an string that correlates to the ID #}
{# of the table that newly created entries should be added to, as well as the "form" #}
{# variable representing the TimeEntryForm given. #}
{% load django_bootstrap5 %}

<form hx-post="{% url 'timekeeping:time-input' %}" hx-target="#table-and-form">
    <div class="row no-gutters">
        {% bootstrap_field form.start_time wrapper_class='form-group col-md-6' %}
        {% bootstrap_field form.end_time wrapper_class='form-group col-md-6' %}
    </div>
    {% bootstrap_form_errors form %}
    <br>

    <button type="submit" value="Save" class="btn btn-outline-primary lh-1">
        <span class="material-icons">check</span>
    </button>
    <button type="button" value="Cancel" class="btn btn-outline-danger lh-1" onClick="this.form.reset()">
        <span class="material-icons">delete</span>
    </button>
</form>

templates/timekeeping/partials/time_entry_form_post.html
<div id="table-and-form">
    <div class="card p-4 mt-2 mb-2" >
        {% include 'timekeeping/partials/create_time_entry.html' with form=form %}
    </div>

    <h2>This Week's Time Entries</h2>
    {% include 'timekeeping/partials/time_table.html' with time_entries=time_entries %}
</div>

templates/timekeeping/partials/time_entry_row.html
<tr>
    <td>{{ time_entry.start_time.date|date:'m/d/Y' }}</td>
    <td>{{ time_entry.start_time.time|date:'H:i' }}</td>
    <td>{{ time_entry.end_time.date|date:'m/d/Y' }}</td>
    <td>{{ time_entry.end_time.time|date:'H:i' }}</td>
    <td class="text-end">{{ time_entry.hours|floatformat:2 }}</td>
</tr>

templates/timekeeping/partials/time_table.html
<table class="table table-striped align-baseline">
    <thead>
        <tr>
            <th>Start Date</th>
            <th>Start Time</th>
            <th>End Date</th>
            <th>End Time</th>
            <th class="text-end hours-col">Hours</th>
        </tr>
    </thead>
    <tbody>
        {% for time_entry in time_entries %}
            {% include 'timekeeping/partials/time_entry_row.html' with time_entry=time_entry %}
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th/>
            <th/>
            <th/>
            <th/>
            <th class="text-end">Total Hours: {{ total_hours }}</th>
        </tr>
    </tfoot>
</table>